In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\sharn\\Downloads\\Kaggel\\rideBookings.csv")
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [3]:
df.shape

(150000, 21)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  str
 1   Time                               150000 non-null  str
 2   Booking ID                         150000 non-null  str
 3   Booking Status                     150000 non-null  str
 4   Customer ID                        150000 non-null  str
 5   Vehicle Type                       150000 non-null  str
 6   Pickup Location                    150000 non-null  str
 7   Drop Location                      150000 non-null  str
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   str
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   str
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    str
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  str
dtypes: float64(9), str(12)
memory usage: 24.0 MB

In [5]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [6]:
mean = df["Avg VTAT"].mean().round(2)
df["Avg VTAT"]=df["Avg VTAT"].fillna(mean)
df["Avg VTAT"].head()

0     8.46
1     4.90
2    13.40
3    13.10
4     5.30
Name: Avg VTAT, dtype: float64

In [7]:
mean1 = df["Avg CTAT"].mean()
df["Avg CTAT"] = df["Avg CTAT"].fillna(mean1.round(2))

In [8]:

df["Cancelled Rides by Customer"] = df["Cancelled Rides by Customer"].fillna("Data not provide")

In [9]:

df["Reason for cancelling by Customer"] =df["Reason for cancelling by Customer"].fillna("Data not provide")

In [10]:

df["Cancelled Rides by Driver"] =df["Cancelled Rides by Driver"].fillna("Detail not provide")

In [11]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                                  0
Avg CTAT                                  0
Cancelled Rides by Customer               0
Reason for cancelling by Customer         0
Cancelled Rides by Driver                 0
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [12]:
df["Driver Cancellation Reason"] =df["Driver Cancellation Reason"].fillna("Data not provide")

In [13]:
mean3 = df["Incomplete Rides"].mean()
df["Incomplete Rides"] =df["Incomplete Rides"].fillna(mean3)

In [14]:
mode3 = df["Incomplete Rides Reason"].mode()
df["Incomplete Rides Reason"] =df["Incomplete Rides Reason"].fillna(mode3[0])

In [15]:
mean4 = df["Booking Value"].mean()
df["Booking Value"] =df["Booking Value"].fillna(mean4)

In [16]:
mean5 = df["Ride Distance"].mean()
df["Ride Distance"] = df["Ride Distance"].fillna(mean5)

In [17]:
mode4 = df["Driver Ratings"].mode()
df["Driver Ratings"] = df["Driver Ratings"].fillna(mode4[0])

In [18]:
mode5 = df["Payment Method"].mode()
df["Payment Method"] = df["Payment Method"].fillna(mode5[0])

In [19]:
df.isnull().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                                 0
Avg CTAT                                 0
Cancelled Rides by Customer              0
Reason for cancelling by Customer        0
Cancelled Rides by Driver                0
Driver Cancellation Reason               0
Incomplete Rides                         0
Incomplete Rides Reason                  0
Booking Value                            0
Ride Distance                            0
Driver Ratings                           0
Customer Rating                      57000
Payment Method                           0
dtype: int64

In [20]:
mode6 = df["Customer Rating"].mode()
df["Customer Rating"] = df["Customer Rating"].fillna(mode6[0])

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.describe()

,Avg VTAT,Avg CTAT,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,150000.000000,150000.000000,150000.0,150000.000000,150000.000000,150000.000000,150000.000000
mean,8.456607,29.149753,1.0,508.295912,24.637012,4.257215,4.592842
std,3.639092,7.341242,0.0,326.389291,11.546441,0.345619,0.420321
min,2.000000,10.000000,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.600000,25.000000,1.0,319.750000,17.360000,4.200000,4.300000
50%,8.460000,29.150000,1.0,508.295912,24.637012,4.300000,4.800000
75%,11.000000,32.900000,1.0,521.000000,30.650000,4.300000,4.900000
max,20.000000,45.000000,1.0,4277.000000,50.000000,5.000000,5.000000

In [23]:
df["Drop Location"].value_counts()

Drop Location
Ashram              936
Basai Dhankot       917
Lok Kalyan Marg     916
Narsinghpur         913
Cyber Hub           912
                   ...
MG Road             799
Bhiwadi             792
Shivaji Park        786
Anand Vihar ISBT    784
Huda City Centre    774
Name: count, Length: 176, dtype: int64

In [24]:
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,8.46,29.15,...,Data not provide,Detail not provide,Data not provide,1.0,Customer Demand,508.295912,24.637012,4.3,4.9,UPI
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.90,14.00,...,Data not provide,Detail not provide,Data not provide,1.0,Vehicle Breakdown,237.000000,5.730000,4.3,4.9,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.40,25.80,...,Data not provide,Detail not provide,Data not provide,1.0,Customer Demand,627.000000,13.580000,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.10,28.50,...,Data not provide,Detail not provide,Data not provide,1.0,Customer Demand,416.000000,34.020000,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.30,19.60,...,Data not provide,Detail not provide,Data not provide,1.0,Customer Demand,737.000000,48.210000,4.1,4.3,UPI

In [25]:
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

In [27]:
df["Vehicle Type"].value_counts()

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64